name: Docker Image and Push CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Docker
      uses: actions/checkout@v2
      
    - name: Login DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PSW }}
    
    - name: Build the Docker image
      run: docker build -t hello-world-ss .
    
    - name: Tag the Docker image
      run: docker tag hello-world-ss ${{ secrets.DOCKERHUB_USER }}/hello-world-ss
      
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USER }}/hello-world-ss
